spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com:
      jotapem: INFO