spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATASOURCE_URL:jdbc:postgresql://localhost:5432/your_account_db}
    username: ${JDBC_DATASOURCE_USERNAME:postgres}
    password: ${JDBC_DATASOURCE_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com:
      jotapem: DEBUG