spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATASOURCE_URL}
    username: ${JDBC_DATASOURCE_USERNAME}
    password: ${JDBC_DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

logging:
  level:
    com:
      jotapem: DEBUG